/*
This file is used to serve the docs generated by Sphinx

Usage: node app.js
*/
const express = require('express');
const app = express();
const port = 3000;

app.use(express.static('docs/_build/html'));

app.listen(port, () => {
  console.log(`Serving Sphinx documentation files on ${port}`)
});
